######################################################################
# Automatically generated by qmake (3.0) qui jul 7 11:32:52 2016
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

# Input
SOURCES += main.cpp
